### ISSUE TITLE
Zapper build does not handle pip install failures (should fail)

### ISSUE THREAD

**Issue by Rapportus** [MaxPoint/Zapper#1]
Zapper should fail out with a nonzero exit code when pip install -r requirements.txt fails to install dependencies (either flavor from config).

**Comment by blakfeld** [comment]
I just saw this bug! Sorry, I was out of town all month. Either way, I'm supposed to have write access to this repo, but apparently I don't? I submitted a pull request, so the second someone wants to click that merge button it should be g2g.

**Comment by DCHougland** [comment]
I went ahead and merged the pull request as well as fixed the setting to make you Admin.

Damon
